"""Convert ALOHA-style HDF5 data to LeRobot v2.0 format, with episode origin tracking.

This is a drop-in replacement for examples/aloha_real/convert_aloha_data_to_lerobot_robotwin.py.

Main addition:
  When a multi-task training_data directory is converted into a single LeRobot repo,
  this script writes:

    <HF_LEROBOT_HOME>/<repo_id>/meta/episode_origin.jsonl

  Each row maps LeRobot global episode_index back to:
    task_name / task_config / local_episode_index / source_episode_index / episode_length.

Expected raw_dir layout:
  raw_dir/
    episode_origin_local.jsonl        # recommended, generated by prepare_multitask_training_data.py
    <task_name>/
      episode_0/
        instructions.json
        episode_0.hdf5
      episode_1/
        instructions.json
        episode_1.hdf5
      ...
"""

from __future__ import annotations

import dataclasses
import fnmatch
import json
import os
import re
import shutil
from pathlib import Path
from typing import Literal

import h5py
import numpy as np
import torch
import tqdm
import tyro
from lerobot.common.datasets.lerobot_dataset import HF_LEROBOT_HOME
from lerobot.common.datasets.lerobot_dataset import LeRobotDataset


@dataclasses.dataclass(frozen=True)
class DatasetConfig:
    use_videos: bool = True
    tolerance_s: float = 0.0001
    image_writer_processes: int = 10
    image_writer_threads: int = 5
    video_backend: str | None = None


DEFAULT_DATASET_CONFIG = DatasetConfig()
EPISODE_RE = re.compile(r"episode_(\d+)")


def create_empty_dataset(
    repo_id: str,
    robot_type: str,
    mode: Literal["video", "image"] = "video",
    *,
    has_velocity: bool = False,
    has_effort: bool = False,
    dataset_config: DatasetConfig = DEFAULT_DATASET_CONFIG,
) -> LeRobotDataset:
    motors = [
        "left_waist",
        "left_shoulder",
        "left_elbow",
        "left_forearm_roll",
        "left_wrist_angle",
        "left_wrist_rotate",
        "left_gripper",
        "right_waist",
        "right_shoulder",
        "right_elbow",
        "right_forearm_roll",
        "right_wrist_angle",
        "right_wrist_rotate",
        "right_gripper",
    ]
    cameras = ["cam_high", "cam_left_wrist", "cam_right_wrist"]

    features = {
        "observation.state": {
            "dtype": "float32",
            "shape": (len(motors),),
            "names": [motors],
        },
        "action": {
            "dtype": "float32",
            "shape": (len(motors),),
            "names": [motors],
        },
    }
    if has_velocity:
        features["observation.velocity"] = {
            "dtype": "float32",
            "shape": (len(motors),),
            "names": [motors],
        }
    if has_effort:
        features["observation.effort"] = {
            "dtype": "float32",
            "shape": (len(motors),),
            "names": [motors],
        }
    for cam in cameras:
        features[f"observation.images.{cam}"] = {
            "dtype": mode,
            "shape": (3, 480, 640),
            "names": ["channels", "height", "width"],
        }

    repo_path = HF_LEROBOT_HOME / repo_id
    if repo_path.exists():
        shutil.rmtree(repo_path)

    return LeRobotDataset.create(
        repo_id=repo_id,
        fps=50,
        robot_type=robot_type,
        features=features,
        use_videos=dataset_config.use_videos,
        tolerance_s=dataset_config.tolerance_s,
        image_writer_processes=dataset_config.image_writer_processes,
        image_writer_threads=dataset_config.image_writer_threads,
        video_backend=dataset_config.video_backend,
    )


def has_velocity(hdf5_files: list[Path]) -> bool:
    with h5py.File(hdf5_files[0], "r") as ep:
        return "/observations/qvel" in ep


def has_effort(hdf5_files: list[Path]) -> bool:
    with h5py.File(hdf5_files[0], "r") as ep:
        return "/observations/effort" in ep


def load_raw_images_per_camera(ep: h5py.File, cameras: list[str]) -> dict[str, np.ndarray]:
    imgs_per_cam = {}
    for camera in cameras:
        uncompressed = ep[f"/observations/images/{camera}"].ndim == 4
        if uncompressed:
            imgs_array = ep[f"/observations/images/{camera}"][:]
        else:
            import cv2

            imgs_array = []
            for data in ep[f"/observations/images/{camera}"]:
                data = np.frombuffer(data, np.uint8)
                imgs_array.append(cv2.cvtColor(cv2.imdecode(data, 1), cv2.COLOR_BGR2RGB))
            imgs_array = np.asarray(imgs_array)
        imgs_per_cam[camera] = imgs_array
    return imgs_per_cam


def load_raw_episode_data(
    ep_path: Path,
) -> tuple[dict[str, np.ndarray], torch.Tensor, torch.Tensor, torch.Tensor | None, torch.Tensor | None]:
    with h5py.File(ep_path, "r") as ep:
        state = torch.from_numpy(ep["/observations/qpos"][:])
        action = torch.from_numpy(ep["/action"][:])
        velocity = torch.from_numpy(ep["/observations/qvel"][:]) if "/observations/qvel" in ep else None
        effort = torch.from_numpy(ep["/observations/effort"][:]) if "/observations/effort" in ep else None
        imgs_per_cam = load_raw_images_per_camera(
            ep,
            ["cam_high", "cam_left_wrist", "cam_right_wrist"],
        )
    return imgs_per_cam, state, action, velocity, effort


def episode_sort_key(path: Path) -> tuple[str, int, str]:
    # Expected: raw_dir/<task>/episode_<idx>/episode_<idx>.hdf5
    task = path.parent.parent.name if path.parent.parent != path.parent else ""
    m = EPISODE_RE.search(path.parent.name) or EPISODE_RE.search(path.stem)
    idx = int(m.group(1)) if m else 10**12
    return task, idx, str(path)


def discover_hdf5_files(raw_dir: Path) -> list[Path]:
    hdf5_files: list[Path] = []
    for root, _, files in os.walk(raw_dir):
        for filename in fnmatch.filter(files, "*.hdf5"):
            hdf5_files.append(Path(root) / filename)
    hdf5_files.sort(key=episode_sort_key)
    if not hdf5_files:
        raise FileNotFoundError(f"No .hdf5 files found under {raw_dir}")
    return hdf5_files


def load_local_origin(raw_dir: Path) -> dict[tuple[str, int], dict]:
    path = raw_dir / "episode_origin_local.jsonl"
    print(f"[INFO] Looking for episode origin manifest: {path}")
    if not path.exists():
        print(f"[WARN] Missing episode origin manifest: {path}")
        return {}
    print(f"[INFO] Found episode origin manifest: {path}")
    mapping: dict[tuple[str, int], dict] = {}
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            r = json.loads(line)
            mapping[(r["task_name"], int(r["local_episode_index"]))] = r
    return mapping


def infer_task_and_episode(raw_dir: Path, ep_path: Path) -> tuple[str, int]:
    rel = ep_path.relative_to(raw_dir)
    # Expected: <task>/episode_<idx>/episode_<idx>.hdf5
    if len(rel.parts) >= 3:
        task_name = rel.parts[0]
    else:
        task_name = "unknown_task"
    m = EPISODE_RE.search(ep_path.parent.name) or EPISODE_RE.search(ep_path.stem)
    if not m:
        raise ValueError(f"Cannot infer episode index from path: {ep_path}")
    return task_name, int(m.group(1))


def infer_origin_record(
    *,
    raw_dir: Path,
    ep_path: Path,
    local_origin: dict[tuple[str, int], dict],
    default_clean_config: str,
    default_randomized_config: str,
    clean_num: int,
    global_episode_index: int,
    episode_length: int,
) -> dict:
    task_name, local_episode_index = infer_task_and_episode(raw_dir, ep_path)

    base = {
        "global_episode_index": global_episode_index,
        "task_name": task_name,
        "local_episode_index": local_episode_index,
        "episode_length": episode_length,
        "hdf5_path": str(ep_path),
    }

    local = local_origin.get((task_name, local_episode_index))
    if local is not None:
        base.update(
            {
                "task_config": local["task_config"],
                "source_episode_index": int(local["source_episode_index"]),
                "training_episode_dir": local.get("training_episode_dir"),
                "source_episode_dir": local.get("source_episode_dir"),
            }
        )
        return base

    # Fallback for the known convention:
    # local episode 0..clean_num-1 is demo_clean;
    # local episode clean_num.. is demo_randomized with source index shifted back.
    if local_episode_index < clean_num:
        task_config = default_clean_config
        source_episode_index = local_episode_index
    else:
        task_config = default_randomized_config
        source_episode_index = local_episode_index - clean_num

    base.update(
        {
            "task_config": task_config,
            "source_episode_index": source_episode_index,
            "origin_inferred": True,
        }
    )
    return base


def choose_instruction(ep_path: Path) -> str:
    instr_path = ep_path.parent / "instructions.json"
    with instr_path.open("r", encoding="utf-8") as f_instr:
        instruction_dict = json.load(f_instr)
    instructions = instruction_dict["instructions"]
    # Keep the original RoboTwin/OpenPI behavior: randomly select one instruction
    # for this episode during LeRobot conversion. We only add origin metadata;
    # we do not change the training data distribution.
    if isinstance(instructions, list):
        if len(instructions) == 0:
            raise ValueError(f"Empty instructions list in {instr_path}")
        return str(np.random.choice(instructions))
    return str(instructions)


def populate_dataset(
    dataset: LeRobotDataset,
    raw_dir: Path,
    hdf5_files: list[Path],
    *,
    local_origin: dict[tuple[str, int], dict],
    default_clean_config: str,
    default_randomized_config: str,
    clean_num: int,
    episodes: list[int] | None = None,
) -> tuple[LeRobotDataset, list[dict]]:
    if episodes is None:
        episodes = list(range(len(hdf5_files)))

    origin_records: list[dict] = []

    for global_episode_index, list_idx in enumerate(tqdm.tqdm(episodes)):
        ep_path = hdf5_files[list_idx]
        imgs_per_cam, state, action, velocity, effort = load_raw_episode_data(ep_path)
        num_frames = int(state.shape[0])
        instruction = choose_instruction(ep_path)

        origin_records.append(
            infer_origin_record(
                raw_dir=raw_dir,
                ep_path=ep_path,
                local_origin=local_origin,
                default_clean_config=default_clean_config,
                default_randomized_config=default_randomized_config,
                clean_num=clean_num,
                global_episode_index=global_episode_index,
                episode_length=num_frames,
            )
        )

        for i in range(num_frames):
            frame = {
                "observation.state": state[i],
                "action": action[i],
                "task": instruction,
            }
            for camera, img_array in imgs_per_cam.items():
                frame[f"observation.images.{camera}"] = img_array[i]
            if velocity is not None:
                frame["observation.velocity"] = velocity[i]
            if effort is not None:
                frame["observation.effort"] = effort[i]
            dataset.add_frame(frame)
        dataset.save_episode()

    return dataset, origin_records


def write_jsonl(path: Path, records: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for r in records:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def port_aloha(
    raw_dir: Path,
    repo_id: str,
    raw_repo_id: str | None = None,
    task: str = "DEBUG",  # kept for CLI compatibility; per-episode instructions are used.
    *,
    episodes: list[int] | None = None,
    push_to_hub: bool = False,
    is_mobile: bool = False,
    mode: Literal["video", "image"] = "image",
    clean_num: int = 50,
    default_clean_config: str = "demo_clean",
    default_randomized_config: str = "demo_randomized",
    dataset_config: DatasetConfig = DEFAULT_DATASET_CONFIG,
):
    del raw_repo_id, task  # not used in this local conversion path

    if not raw_dir.exists():
        raise FileNotFoundError(f"raw_dir does not exist: {raw_dir}")

    hdf5_files = discover_hdf5_files(raw_dir)
    print(f"[INFO] Found {len(hdf5_files)} hdf5 episodes under {raw_dir}")

    local_origin = load_local_origin(raw_dir)
    if local_origin:
        print(f"[INFO] Loaded local origin records: {len(local_origin)}")
    else:
        print("[WARN] No episode_origin_local.jsonl found. Falling back to clean_num-based inference.")

    dataset = create_empty_dataset(
        repo_id,
        robot_type="mobile_aloha" if is_mobile else "aloha",
        mode=mode,
        has_effort=has_effort(hdf5_files),
        has_velocity=has_velocity(hdf5_files),
        dataset_config=dataset_config,
    )

    dataset, origin_records = populate_dataset(
        dataset,
        raw_dir,
        hdf5_files,
        local_origin=local_origin,
        default_clean_config=default_clean_config,
        default_randomized_config=default_randomized_config,
        clean_num=clean_num,
        episodes=episodes,
    )

    repo_path = HF_LEROBOT_HOME / repo_id
    origin_path = repo_path / "meta" / "episode_origin.jsonl"
    write_jsonl(origin_path, origin_records)
    print(f"[OK] Wrote episode origin manifest: {origin_path}")

    if push_to_hub:
        dataset.push_to_hub()


if __name__ == "__main__":
    tyro.cli(port_aloha)
